import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomMenuBar from "@/components/BottomMenuBar";
import { ThemeProvider } from "@/context/ThemeProvider";
import { AppSettingsProvider } from "@/context/AppSettingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  max-h-[100vh]`}
      ><AppSettingsProvider>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className=" max-w-md mx-auto max-h-full relative dark:shadow-none shadow-md">
            {children}
          </main>
          <BottomMenuBar />
        </ThemeProvider>
        </AppSettingsProvider>
      </body>
    </html>
  );
}
